### ISSUE TITLE
GW170817 PE data file from GWTC-1 is not recognized

### ISSUE THREAD

**Issue by nilsvu** [pesummary/pesummary#1]
The GW170817 data file in the GWTC-1 PE sample release https://dcc.ligo.org/LIGO-P1800370/public has no key `Overall_posterior`, so the `is_GWTC1_file` function https://github.com/pesummary/pesummary/blob/11c980db4e34f0634f5bbca90a999c09ccf394dc/pesummary/gw/file/read.py#L31-L47 does not recognize it. The `GWTC1.load_file` function also relies on the `Overall_posterior`. Do you have a quick and dirty solution for this so I can read in the file anyway?

**Comment by pesummary** [comment]
Hi @nilsleiffischer. Thanks for raising this issue. To prevent the following error from being raised when trying to read in the GW170817 result file:

```python
>>> from pesummary.io import read
>>> f = read("GW170817_GWTC-1.hdf5")
2020-06-14  22:13:11 PESummary WARNING : Using the default load because GW170817_GWTC-1.hdf5 failed the following checks: is_lalinference_file, is_bilby_hdf5_file, is_pesummary_hdf5_file, is_pesummary_hdf5_file_deprecated, is_GWTC1_file
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Charlie/virtualenvs/pesummary_non_gw/lib/python3.6/site-packages/pesummary-0.6.0+4.ge79e242.dirty-py3.6.egg/pesummary/io/read.py", line 42, in read
    return getattr(module, "read")(path, file_format=file_format, **kwargs)
  File "/Users/Charlie/virtualenvs/pesummary_non_gw/lib/python3.6/site-packages/pesummary-0.6.0+4.ge79e242.dirty-py3.6.egg/pesummary/gw/file/read.py", line 107, in read
    file_format=file_format, **kwargs
  File "/Users/Charlie/virtualenvs/pesummary_non_gw/lib/python3.6/site-packages/pesummary-0.6.0+4.ge79e242.dirty-py3.6.egg/pesummary/core/file/read.py", line 300, in read
    return _read(path, options, default=DEFAULT, **kwargs)
  File "/Users/Charlie/virtualenvs/pesummary_non_gw/lib/python3.6/site-packages/pesummary-0.6.0+4.ge79e242.dirty-py3.6.egg/pesummary/core/file/read.py", line 244, in _read
    return default["default"](path, **load_kwargs)
  File "/Users/Charlie/virtualenvs/pesummary_non_gw/lib/python3.6/site-packages/pesummary-0.6.0+4.ge79e242.dirty-py3.6.egg/pesummary/gw/file/formats/default.py", line 81, in load_file
    return cls(path, **kwargs)
  File "/Users/Charlie/virtualenvs/pesummary_non_gw/lib/python3.6/site-packages/pesummary-0.6.0+4.ge79e242.dirty-py3.6.egg/pesummary/gw/file/formats/default.py", line 73, in __init__
    self.path_to_results_file, e
Exception: Failed to read data for file GW170817_GWTC-1.hdf5 because: Found multiple posterior sample tables in 'GW170817_GWTC-1.hdf5': IMRPhenomPv2NRT_highSpin_posterior, IMRPhenomPv2NRT_lowSpin_posterior. Not sure which to load.
```

I have added a `path_to_samples` kwarg (6e04292) which tells the `read` function which posterior table to load. This can be used in the following way:

```python
>>> f = read("GW170817_GWTC-1.hdf5", path_to_samples="IMRPhenomPv2NRT_highSpin_posterior")
>>> f.samples_dict["mass_1"]
Array([1.82241211, 1.69103766, 1.71265053, ..., 1.64822997, 1.53093584,
       1.86249465])
>>> fig = f.samples_dict.plot("mass_1", type="hist", bins=30)
>>> fig.show()
```

The `summarypages` executable can also be used on this result file by passing the `--path_to_samples` command line argument. For example:

```bash
$ summarypages --webdir ./GWTC1 --no_ligo_skymap --samples GWTC-1_sample_release/GW150914_GWTC-1.hdf5 GWTC-1_sample_release/GW170817_GWTC-1.hdf5 --path_to_samples None IMRPhenomPv2NRT_highSpin_posterior --labels GW150914 GW170817 --gw
```

**Comment by nilsvu** [comment]
Thank you for addressing this so quickly :) FYI, I had some issues pip-installing the package at master because
1. `pip install git+https://github.com/pesummary/pesummary.git@master` fails with `Error downloading object: docs/core/summarypages/examples/1d_histogram.png`, probably because it is a GIT LFS reference, and
2. Your installation documentation still mentions the git repository on ligo.org which does not include your recent commits on GitHub.

Cloning this repository and installing the package manually worked fine, but I wanted to make you aware of these issues.
